#ifndef QTPANCOMMON_GLOBAL_H
#define QTPANCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPANCOMMON_LIBRARY)
#  define QTPANCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTPANCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPANCOMMON_GLOBAL_H
